version: '2'
services:
    mariadb:
      image: mariadb:10.2
      environment:
        MYSQL_ROOT_PASSWORD: i34dbkub
        MYSQL_DATABASE: delivery
        MYSQL_USER: delivery
        MYSQL_PASSWORD: delivery
      ports:
        - "3306:3306"
      logging:
        driver: syslog
        options:
          tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
      networks:
        - backend
      restart: on-failure
      volumes:
        - ${PWD}/mariadb:/var/lib/mysql
        - ${PWD}/config:/config
    jliveryws:
      build: .
      volumes:
        - ${PWD}:/jliveryws
      ports:
        - 80:3000
      command: bash -l -c 'yarn install && yarn start'
      links:
        - mariadb
      depends_on:
        - mariadb
      networks:
        - backend

networks:       
  backend:
    driver: bridge
